definitions:
  models.Crdt:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  models.Image:
    properties:
      name:
        type: string
    type: object
  models.ImageWithCID:
    properties:
      cid:
        type: string
      name:
        type: string
    type: object
  models.Strategy:
    properties:
      name:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: a.aksoy@tu-berlin.de
    name: Ahmet Kerem Aksoy
  description: DistroMash meshes your Docker Distribution
  termsOfService: http://swagger.io/terms/
  title: DistroMash API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Get the home page.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: get the home page
      tags:
      - Home
  /api/v1/crdt:
    get:
      consumes:
      - application/json
      description: Get all CRDT key-value pairs.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Crdt'
            type: array
      summary: get all crdt key-value pairs
      tags:
      - Crdt
    post:
      consumes:
      - application/json
      description: Post a CRDT key-value pair.
      parameters:
      - description: Post Crdt
        in: body
        name: crdt
        required: true
        schema:
          $ref: '#/definitions/models.Crdt'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Crdt'
      summary: post crdt key-value pair
      tags:
      - Crdt
  /api/v1/crdt/{key}:
    delete:
      consumes:
      - application/json
      description: Delete a CRDT key-value pair.
      parameters:
      - description: Key of Value
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Crdt'
      summary: delete crdt key-value pair
      tags:
      - Crdt
    get:
      consumes:
      - application/json
      description: Get the CRDT value by key.
      parameters:
      - description: Key of Value
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Crdt'
      summary: get crdt value by given key
      tags:
      - Crdt
  /api/v1/image:
    post:
      consumes:
      - application/json
      description: Upload a multi-platform docker image to ipfs and get the cid.
      parameters:
      - description: Post Image
        in: body
        name: crdt
        required: true
        schema:
          $ref: '#/definitions/models.Image'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ImageWithCID'
      summary: upload a multi-platform docker image to ipfs and get the cid
      tags:
      - Image
  /api/v1/strategy:
    get:
      consumes:
      - application/json
      description: Get all strategies.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Strategy'
            type: array
      summary: get all strategies
      tags:
      - Strategy
    post:
      consumes:
      - application/json
      description: Post the strategy.
      parameters:
      - description: Name of Strategy
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Strategy'
      summary: post the strategy
      tags:
      - Strategy
  /api/v1/strategy/{name}:
    get:
      consumes:
      - application/json
      description: Get the strategy.
      parameters:
      - description: Name of Strategy
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Strategy'
      summary: get the strategy
      tags:
      - Strategy
  /api/v1/strategy/registered:
    get:
      consumes:
      - application/json
      description: Get registered strategies.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Strategy'
            type: array
      summary: get registered strategies
      tags:
      - Strategy
swagger: "2.0"
